-- Purity Ritual — Sprint 1
create extension if not exists pgcrypto;
create table if not exists public.pr_profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',phone text,role text not null default 'customer' check(role in('customer','admin','sales','operations')),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create sequence if not exists public.pr_request_no_seq start 1;
create table if not exists public.pr_service_requests(id uuid primary key default gen_random_uuid(),request_no text not null unique,customer_id uuid not null references public.pr_profiles(id),service_type text not null,property_type text not null,city text not null default 'جدة',district text not null,address text not null,area_sqm numeric(12,2),preferred_date date,notes text,status text not null default 'new' check(status in('new','reviewing','inspection_scheduled','quoted','approved','scheduled','in_progress','completed','cancelled')),admin_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.pr_request_attachments(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.pr_service_requests(id) on delete cascade,customer_id uuid not null references public.pr_profiles(id),storage_path text not null unique,file_name text not null,mime_type text,file_size bigint,created_at timestamptz not null default now());
create or replace function public.pr_set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end;$$;
create or replace function public.pr_set_request_no() returns trigger language plpgsql as $$ begin if new.request_no is null or new.request_no='' then new.request_no='PR-REQ-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.pr_request_no_seq')::text,4,'0');end if;return new;end;$$;
create or replace function public.pr_handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.pr_profiles(id,full_name,phone) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.raw_user_meta_data->>'phone') on conflict(id) do nothing;return new;end;$$;
drop trigger if exists pr_on_auth_user_created on auth.users;create trigger pr_on_auth_user_created after insert on auth.users for each row execute procedure public.pr_handle_new_user();
drop trigger if exists pr_requests_number on public.pr_service_requests;create trigger pr_requests_number before insert on public.pr_service_requests for each row execute procedure public.pr_set_request_no();
drop trigger if exists pr_requests_updated on public.pr_service_requests;create trigger pr_requests_updated before update on public.pr_service_requests for each row execute procedure public.pr_set_updated_at();
create or replace function public.pr_is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.pr_profiles where id=auth.uid() and role in('admin','sales','operations') and is_active=true);$$;
alter table public.pr_profiles enable row level security;alter table public.pr_service_requests enable row level security;alter table public.pr_request_attachments enable row level security;
revoke update on public.pr_profiles from authenticated;grant update(full_name,phone) on public.pr_profiles to authenticated;
drop policy if exists "profiles own read" on public.pr_profiles;create policy "profiles own read" on public.pr_profiles for select using(id=auth.uid() or public.pr_is_staff());
drop policy if exists "profiles own update" on public.pr_profiles;create policy "profiles own update" on public.pr_profiles for update using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists "requests customer read" on public.pr_service_requests;create policy "requests customer read" on public.pr_service_requests for select using(customer_id=auth.uid() or public.pr_is_staff());
drop policy if exists "requests customer create" on public.pr_service_requests;create policy "requests customer create" on public.pr_service_requests for insert with check(customer_id=auth.uid());
drop policy if exists "requests staff update" on public.pr_service_requests;create policy "requests staff update" on public.pr_service_requests for update using(public.pr_is_staff()) with check(public.pr_is_staff());
drop policy if exists "attachments customer read" on public.pr_request_attachments;create policy "attachments customer read" on public.pr_request_attachments for select using(customer_id=auth.uid() or public.pr_is_staff());
drop policy if exists "attachments customer create" on public.pr_request_attachments;create policy "attachments customer create" on public.pr_request_attachments for insert with check(customer_id=auth.uid());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('service-request-photos','service-request-photos',false,5242880,array['image/jpeg','image/png','image/webp','image/heic']) on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "request photos customer upload" on storage.objects;create policy "request photos customer upload" on storage.objects for insert to authenticated with check(bucket_id='service-request-photos' and(storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "request photos customer read" on storage.objects;create policy "request photos customer read" on storage.objects for select to authenticated using(bucket_id='service-request-photos' and((storage.foldername(name))[1]=auth.uid()::text or public.pr_is_staff()));
create index if not exists pr_requests_customer_idx on public.pr_service_requests(customer_id,created_at desc);create index if not exists pr_requests_status_idx on public.pr_service_requests(status,created_at desc);
-- ترقية حساب الإدارة:
-- update public.pr_profiles set role='admin' where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL');
